# Generated by Django 2.0 on 2021-02-05 04:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0002_auto_20210128_1247'),
    ]

    operations = [
        migrations.AddField(
            model_name='stock',
            name='location',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
